[workspace]
members = ["crates/*"]
# Only check / build main crates by default (check all with `--workspace`)
default-members = []
resolver = "3"

[workspace.dependencies]
candle-transformers = "0.9.1"
